sudo: false

services:
  - docker

before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - compile

jobs:
  include:
    - stage: compile
      language: java
      jdk: openjdk8
      install: true
      before_script:
        - cd gateway
      script:
        - ./gradlew build --scan -s
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - test $TRAVIS_BRANCH = "master" && docker build -t bwvolleyball/gateway . && docker push bwvolleyball/gateway
    - stage: compile
      language: java
      jdk: openjdk8
      install: true
      before_script:
        - cd auth-api
      script:
        - ./gradlew build --scan -s
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - test $TRAVIS_BRANCH = "master" && docker build -t bwvolleyball/auth-api . && docker push bwvolleyball/auth-api
    - stage: compile
      language: java
      jdk: openjdk8
      install: true
      before_script:
        - cd recipe-api
      script:
        - ./gradlew build --scan -s
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - test $TRAVIS_BRANCH = "master" && docker build -t bwvolleyball/recipe-api . && docker push bwvolleyball/recipe-api
    - stage: compile
      language: java
      jdk: openjdk8
      install: true
      before_script:
        - cd cookbook-api
      script:
        - ./gradlew build --scan -s
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - test $TRAVIS_BRANCH = "master" && docker build -t bwvolleyball/cookbook-api . && docker push bwvolleyball/cookbook-api
    - stage: compile
      language: java
      jdk: openjdk8
      install: true
      before_script:
        - cd swagger-api
      script:
        - ./gradlew build --scan -s
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - test $TRAVIS_BRANCH = "master" && docker build -t bwvolleyball/swagger-api . && docker push bwvolleyball/swagger-api
    - stage: compile
      language: node_js
      node_js: lts/*
      before_script:
        - npm install -g @angular/cli
        - cd recipe-organizr-ui
      script:
        - npm ci
        - ng lint recipe-organizr-ui
        - ng build --prod --aot
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - test $TRAVIS_BRANCH = "master" && docker build -t bwvolleyball/recipe-organizr-ui . && docker push bwvolleyball/recipe-organizr-ui
