version: '3'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    networks:
      localnet:
        aliases:
          - postgres.local
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '34580:34580'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 34580
    volumes:
      - ./docker/pgadmin/:/var/lib/pgadmin/
    networks:
      - localnet
  recipe-organizr-ui:
    image: bwvolleyball/recipe-organizr-ui
    ports:
      - '4200:80'
    networks:
      localnet:
        aliases:
          - spa.local
  gateway:
    image: bwvolleyball/gateway
    ports:
      - '8079:8079'
      - '8080:8080'
    environment:
      SERVER_PORT: 8080
      AUTH_API_HOST: host.docker.internal
      RECIPE_API_HOST: host.docker.internal
      COOKBOOK_API_HOST: host.docker.internal
      SWAGGER_API_HOST: host.docker.internal
      SPA_HOST: host.docker.internal
  auth-api:
    image: bwvolleyball/auth-api
    ports:
      - '8181:8181'
    environment:
      SERVER_PORT: 8181
      DATABASE_HOST: postgres.local
    networks:
      localnet:
        aliases:
          - auth.local
  recipe-api:
    image: bwvolleyball/recipe-api
    ports:
      - '8282:8282'
    environment:
      SERVER_PORT: 8282
      DATABASE_HOST: postgres.local
    networks:
      localnet:
        aliases:
          - recipe.local
  cookbook-api:
    image: bwvolleyball/cookbook-api
    ports:
      - '8383:8383'
    environment:
      SERVER_PORT: 8383
      DATABASE_HOST: postgres.local
    networks:
      localnet:
        aliases:
          - cookbook.local
  swagger-api:
    image: bwvolleyball/swagger-api
    ports:
      - '8484:8484'
    environment:
      SERVER_PORT: 8484
    networks:
      localnet:
          aliases:
            - swagger.local
networks:
  localnet:
