spring:
  cloud:
    gateway:
      routes:
        - id: auth-api
          uri: http://${bwvolleyball.hosts.auth-api}:8181
          predicates:
            - Path=/api/auth/**
        # The default, catch-all route sends items to the Angular SPA.
        - id: spa
          uri: http://${bwvolleyball.hosts.spa}:4200
          predicates:
            - After=1970-01-01T00:00:00.000-00:00[America/Denver]
bwvolleyball:
  hosts:
    auth-api: ${AUTH_API_HOST:localhost}
    spa: ${SPA_HOST:localhost}
