server:
  port: 8181

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false

bwvolleyball:
  auth:
    okta-domain: dev-331898.okta.com
