version: '3'
services:
  recipe-organizr-ui:
    image: bwvolleyball/recipe-organizr-ui
    ports:
      - '4200:80'
    logging:
      driver: gcplogs
    networks:
      internal:
        aliases:
          - spa.local
  gateway:
    image: bwvolleyball/gateway
    ports:
      - '80:8079'
      - '443:8080'
    volumes:
      - ssl:/etc/letsencrypt
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: gcp
      AUTH_API_HOST: 35.233.144.68
      RECIPE_API_HOST: 35.233.144.68
      COOKBOOK_API_HOST: 35.233.144.68
      SPA_HOST: 35.233.144.68
      PUBLIC_HTTPS_PORT: 443
      SERVER_HTTPS_ONLY: 'true'
      GATEWAY_SSL_PATH: /etc/letsencrypt/live/recipe-organizr.me/keystore.p12
      GATEWAY_SSL_PASSWORD: recipeSSL7
      GATEWAY_SSL_ALIAS: recipe-organizr
    logging:
      driver: gcplogs
  auth-api:
    image: bwvolleyball/auth-api
    ports:
      - '8181:8181'
    environment:
      SERVER_PORT: 8181
      SPRING_PROFILES_ACTIVE: gcp
      DATABASE_HOST: 35.247.110.8
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: '%59Z$$T!bBZT9#p'
    logging:
      driver: gcplogs
    networks:
      internal:
        aliases:
          - auth.local
  recipe-api:
    image: bwvolleyball/recipe-api
    ports:
      - '8282:8282'
    environment:
      SERVER_PORT: 8282
      SPRING_PROFILES_ACTIVE: gcp
      DATABASE_HOST: 35.247.110.8
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: '%59Z$$T!bBZT9#p'
    logging:
      driver: gcplogs
    networks:
      internal:
        aliases:
          - recipe.local
  cookbook-api:
    image: bwvolleyball/cookbook-api
    ports:
      - '8383:8383'
    environment:
      SERVER_PORT: 8383
      SPRING_PROFILES_ACTIVE: gcp
      DATABASE_HOST: 35.247.110.8
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: '%59Z$$T!bBZT9#p'
    logging:
      driver: gcplogs
    networks:
      internal:
        aliases:
          - cookbook.local
networks:
  internal:
volumes:
  ssl:
    external: true
